modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fc_vanilla"
version = "${version}"
displayName = "Folkcraft Vanilla"
authors = "ENC_Euphony"
description = '''
Some interesting little things.
'''
#logoFile = ""

[[dependencies.fc_vanilla]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fc_vanilla]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fc_vanilla]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "fc_vanilla.mixins.json"
